#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Thu Nov 12 23:01:15 2020
#

import numpy as np
import wx
import wx.lib.agw.aui as aui

from matplotlib.widgets import RectangleSelector
import matplotlib as mpl
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg as NavigationToolbar
from pydicom import dcmread

import tifffile as tiff
from skimage.transform import rescale